import type { ProjectConfig } from './types'

export function generateSitemapXml(config: ProjectConfig): string {
  const domain = config.domain.replace(/^https?:\/\//, '').replace(/\/$/, '')
  const baseUrl = `https://${domain}`
  const today = new Date().toISOString().split('T')[0]

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${baseUrl}/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>${baseUrl}/privacy/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.3</priority>
  </url>
</urlset>`
}

export function generateRobotsTxt(config: ProjectConfig): string {
  const domain = config.domain.replace(/^https?:\/\//, '').replace(/\/$/, '')
  return `User-agent: *
Allow: /
Disallow: /api/

Sitemap: https://${domain}/sitemap.xml`
}

export function generateCreateTableSql(config: ProjectConfig): string {
  const table = config.tableName.trim().toLowerCase()

  return `-- =============================================================================
-- CREATE TABLE: ${table}
-- Lead capture table for ${config.projectName}
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.${table} (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  phone TEXT,
  is_broker BOOLEAN DEFAULT FALSE,
  source TEXT,
  page_path TEXT DEFAULT '/',
  notes TEXT,
  call_count INTEGER DEFAULT 0,
  lead_temperature TEXT DEFAULT 'new',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_${table}_email ON public.${table}(email);
CREATE INDEX IF NOT EXISTS idx_${table}_created ON public.${table}(created_at DESC);
`
}

export function generateFaviconSvg(projectName: string): string {
  const initials = projectName
    .split(/\s+/)
    .slice(0, 2)
    .map((w) => w[0]?.toUpperCase() || '')
    .join('')

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <rect width="32" height="32" rx="8" fill="#1a1a2e"/>
  <text x="16" y="21" text-anchor="middle" fill="white" font-family="Arial,sans-serif" font-weight="700" font-size="14">${initials}</text>
</svg>`
}
