import type { ProjectConfig, GeneratedContent } from './types'

type TemplateGenerator = (config: ProjectConfig, content: GeneratedContent) => string

const esc = (s: string) => s.replace(/'/g, "\\'").replace(/\\/g, '\\\\')

function faqAccordionComponent(): string {
  return [
    "'use client'",
    '',
    "import { useState } from 'react'",
    '',
    'function FAQ({ question, answer }: { question: string; answer: string }) {',
    '  const [open, setOpen] = useState(false)',
    '  return (',
    '    <div className="border-b border-gray-200">',
    '      <button',
    '        type="button"',
    '        onClick={() => setOpen(!open)}',
    '        className="flex w-full items-center justify-between py-5 text-left"',
    '      >',
    '        <span className="text-base font-medium text-gray-900">{question}</span>',
    '        <span className="ml-4 text-xl text-gray-400">{open ? "−" : "+"}</span>',
    '      </button>',
    '      {open && <p className="pb-5 text-sm leading-relaxed text-gray-600">{answer}</p>}',
    '    </div>',
    '  )',
    '}',
  ].join('\n')
}

function buildFeaturesArray(content: GeneratedContent): string {
  if (content.features.length === 0) return '[]'
  const items = content.features.map(
    (f) => `  { icon: '${esc(f.icon)}', title: '${esc(f.title)}', description: '${esc(f.description)}' }`
  )
  return '[\n' + items.join(',\n') + '\n]'
}

function buildFaqsArray(content: GeneratedContent): string {
  if (content.faqs.length === 0) return '[]'
  const items = content.faqs.map(
    (f) => `  { question: '${esc(f.question)}', answer: '${esc(f.answer)}' }`
  )
  return '[\n' + items.join(',\n') + '\n]'
}

// ── Template 1: Hero Focus ──────────────────────────────────────────────────────

const heroFocus: TemplateGenerator = (config, content) => {
  const lines = [
    faqAccordionComponent(),
    '',
    "import LeadForm from '@/components/LeadForm'",
    "import Footer from '@/components/Footer'",
    '',
    'const features = ' + buildFeaturesArray(content),
    '',
    'const faqs = ' + buildFaqsArray(content),
    '',
    'export default function HomePage() {',
    '  return (',
    '    <>',
    '      {/* Hero */}',
    '      <header className="relative min-h-[90vh] flex items-center bg-gray-900">',
    '        <div className="absolute inset-0 bg-[url(/images/hero.jpg)] bg-cover bg-center opacity-40" />',
    '        <div className="absolute inset-0 bg-gradient-to-r from-gray-900/90 via-gray-900/60 to-transparent" />',
    '        <div className="relative z-10 mx-auto w-full max-w-7xl px-4 sm:px-6 py-20">',
    '          <div className="grid gap-12 lg:grid-cols-2 lg:gap-16 items-center">',
    '            <div className="fade-in">',
    '              <h1 className="text-4xl font-extrabold text-white sm:text-5xl lg:text-6xl leading-tight">',
    "                " + esc(content.heroHeadline),
    '              </h1>',
    '              <p className="mt-6 text-lg text-gray-300 max-w-xl leading-relaxed">',
    "                " + esc(content.heroSubheadline),
    '              </p>',
    config.priceRange ? '              <p className="mt-4 text-2xl font-bold text-white">' + esc(config.priceRange) + '</p>' : '',
    '            </div>',
    '            <div className="slide-up rounded-2xl bg-white p-8 shadow-2xl">',
    '              <h2 className="text-xl font-bold text-gray-900 mb-1">' + esc(content.ctaText) + '</h2>',
    '              <p className="text-sm text-gray-500 mb-6">Get floor plans, pricing & VIP access</p>',
    '              <LeadForm />',
    '            </div>',
    '          </div>',
    '        </div>',
    '      </header>',
    '',
    '      <main>',
    '        {/* About */}',
    '        <section className="py-20 px-4 sm:px-6">',
    '          <div className="mx-auto max-w-4xl text-center">',
    '            <h2 className="text-3xl font-bold text-gray-900 sm:text-4xl">About ' + esc(config.projectName) + '</h2>',
    '            <div className="mt-8 text-gray-600 leading-relaxed text-lg whitespace-pre-line">',
    "              {'" + esc(content.aboutSection) + "'}",
    '            </div>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Features */}',
    '        <section className="py-20 px-4 sm:px-6 bg-gray-50">',
    '          <div className="mx-auto max-w-6xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">Key Features</h2>',
    '            <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">',
    '              {features.map((f, i) => (',
    '                <div key={i} className="rounded-xl bg-white p-6 shadow-sm border border-gray-100 hover:shadow-md transition-shadow">',
    '                  <span className="text-3xl">{f.icon}</span>',
    '                  <h3 className="mt-4 text-lg font-semibold text-gray-900">{f.title}</h3>',
    '                  <p className="mt-2 text-sm text-gray-600 leading-relaxed">{f.description}</p>',
    '                </div>',
    '              ))}',
    '            </div>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Location */}',
    '        <section className="py-20 px-4 sm:px-6">',
    '          <div className="mx-auto max-w-4xl text-center">',
    '            <h2 className="text-3xl font-bold text-gray-900 mb-8">Location & Neighborhood</h2>',
    '            <p className="text-gray-600 leading-relaxed text-lg whitespace-pre-line">',
    "              {'" + esc(content.locationDescription) + "'}",
    '            </p>',
    '          </div>',
    '        </section>',
    '',
    '        {/* FAQ */}',
    '        <section className="py-20 px-4 sm:px-6 bg-gray-50">',
    '          <div className="mx-auto max-w-3xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">Frequently Asked Questions</h2>',
    '            <div className="divide-y divide-gray-200 rounded-xl bg-white px-6 shadow-sm border border-gray-100">',
    '              {faqs.map((f, i) => (',
    '                <FAQ key={i} question={f.question} answer={f.answer} />',
    '              ))}',
    '            </div>',
    '          </div>',
    '        </section>',
    '      </main>',
    '',
    '      {/* Mobile Sticky CTA */}',
    '      <div className="fixed bottom-0 left-0 right-0 z-50 bg-white border-t border-gray-200 p-3 md:hidden">',
    '        <a href="#top" className="block w-full rounded-lg bg-[#e2725b] py-3 text-center text-sm font-semibold text-white">',
    '          ' + esc(content.ctaText),
    '        </a>',
    '      </div>',
    '',
    '      <Footer />',
    '    </>',
    '  )',
    '}',
    '',
  ]
  return lines.filter((l) => l !== '').join('\n') + '\n'
}

// ── Template 2: Split Layout ────────────────────────────────────────────────────

const splitLayout: TemplateGenerator = (config, content) => {
  const lines = [
    faqAccordionComponent(),
    '',
    "import LeadForm from '@/components/LeadForm'",
    "import Footer from '@/components/Footer'",
    '',
    'const features = ' + buildFeaturesArray(content),
    'const faqs = ' + buildFaqsArray(content),
    '',
    'export default function HomePage() {',
    '  return (',
    '    <>',
    '      {/* Hero Banner */}',
    '      <header className="relative h-64 sm:h-80 flex items-end bg-gray-900">',
    '        <div className="absolute inset-0 bg-[url(/images/hero.jpg)] bg-cover bg-center opacity-30" />',
    '        <div className="absolute inset-0 bg-gradient-to-t from-gray-900 to-transparent" />',
    '        <div className="relative z-10 mx-auto w-full max-w-7xl px-4 sm:px-6 pb-10">',
    '          <h1 className="text-3xl font-extrabold text-white sm:text-4xl lg:text-5xl">' + esc(content.heroHeadline) + '</h1>',
    '          <p className="mt-3 text-lg text-gray-300 max-w-2xl">' + esc(content.heroSubheadline) + '</p>',
    '        </div>',
    '      </header>',
    '',
    '      <div className="mx-auto max-w-7xl px-4 sm:px-6 py-12">',
    '        <div className="grid gap-12 lg:grid-cols-3">',
    '          {/* Content Column */}',
    '          <main className="lg:col-span-2 space-y-16">',
    '            <section>',
    '              <h2 className="text-2xl font-bold text-gray-900 mb-6">About ' + esc(config.projectName) + '</h2>',
    '              <p className="text-gray-600 leading-relaxed whitespace-pre-line">',
    "                {'" + esc(content.aboutSection) + "'}",
    '              </p>',
    '            </section>',
    '',
    '            <section>',
    '              <h2 className="text-2xl font-bold text-gray-900 mb-6">Key Features</h2>',
    '              <div className="grid gap-6 sm:grid-cols-2">',
    '                {features.map((f, i) => (',
    '                  <div key={i} className="flex gap-4 p-4 rounded-lg border border-gray-100">',
    '                    <span className="text-2xl shrink-0">{f.icon}</span>',
    '                    <div>',
    '                      <h3 className="font-semibold text-gray-900">{f.title}</h3>',
    '                      <p className="mt-1 text-sm text-gray-600">{f.description}</p>',
    '                    </div>',
    '                  </div>',
    '                ))}',
    '              </div>',
    '            </section>',
    '',
    '            <section>',
    '              <h2 className="text-2xl font-bold text-gray-900 mb-6">Location</h2>',
    '              <p className="text-gray-600 leading-relaxed whitespace-pre-line">',
    "                {'" + esc(content.locationDescription) + "'}",
    '              </p>',
    '            </section>',
    '',
    '            <section>',
    '              <h2 className="text-2xl font-bold text-gray-900 mb-8">FAQ</h2>',
    '              <div className="rounded-xl border border-gray-200 px-6">',
    '                {faqs.map((f, i) => <FAQ key={i} question={f.question} answer={f.answer} />)}',
    '              </div>',
    '            </section>',
    '          </main>',
    '',
    '          {/* Sticky Form Column */}',
    '          <aside className="lg:col-span-1">',
    '            <div className="sticky top-8 rounded-2xl border border-gray-200 bg-white p-6 shadow-lg">',
    '              <h2 className="text-lg font-bold text-gray-900 mb-1">' + esc(content.ctaText) + '</h2>',
    '              <p className="text-sm text-gray-500 mb-5">Get exclusive pricing & floor plans</p>',
    '              <LeadForm compact />',
    '            </div>',
    '          </aside>',
    '        </div>',
    '      </div>',
    '',
    '      <div className="fixed bottom-0 left-0 right-0 z-50 bg-white border-t border-gray-200 p-3 lg:hidden">',
    '        <a href="#top" className="block w-full rounded-lg bg-[#e2725b] py-3 text-center text-sm font-semibold text-white">' + esc(content.ctaText) + '</a>',
    '      </div>',
    '',
    '      <Footer />',
    '    </>',
    '  )',
    '}',
    '',
  ]
  return lines.join('\n')
}

// ── Template 3: Storytelling Scroll ─────────────────────────────────────────────

const storytelling: TemplateGenerator = (config, content) => {
  const lines = [
    faqAccordionComponent(),
    '',
    "import LeadForm from '@/components/LeadForm'",
    "import Footer from '@/components/Footer'",
    '',
    'const features = ' + buildFeaturesArray(content),
    'const faqs = ' + buildFaqsArray(content),
    '',
    'export default function HomePage() {',
    '  return (',
    '    <>',
    '      {/* Hero */}',
    '      <header className="relative flex min-h-screen items-center justify-center bg-gray-900 text-center">',
    '        <div className="absolute inset-0 bg-[url(/images/hero.jpg)] bg-cover bg-center opacity-30" />',
    '        <div className="absolute inset-0 bg-gradient-to-b from-gray-900/50 via-gray-900/70 to-gray-900" />',
    '        <div className="relative z-10 px-4 py-24 fade-in">',
    '          <h1 className="text-4xl font-extrabold text-white sm:text-5xl lg:text-7xl tracking-tight">' + esc(content.heroHeadline) + '</h1>',
    '          <p className="mt-6 text-xl text-gray-300 max-w-2xl mx-auto">' + esc(content.heroSubheadline) + '</p>',
    config.priceRange ? '          <p className="mt-4 text-3xl font-bold text-white">' + esc(config.priceRange) + '</p>' : '',
    '          <a href="#register" className="mt-8 inline-block rounded-lg bg-[#e2725b] px-8 py-4 text-sm font-semibold text-white hover:bg-[#d4604a] transition-colors">' + esc(content.ctaText) + '</a>',
    '        </div>',
    '      </header>',
    '',
    '      <main>',
    '        {/* First Form */}',
    '        <section id="register" className="py-20 px-4 sm:px-6 bg-white">',
    '          <div className="mx-auto max-w-lg text-center">',
    '            <h2 className="text-2xl font-bold text-gray-900 mb-2">' + esc(content.ctaText) + '</h2>',
    '            <p className="text-gray-500 mb-8">Be the first to receive pricing, floor plans, and updates</p>',
    '            <LeadForm />',
    '          </div>',
    '        </section>',
    '',
    '        {/* About */}',
    '        <section className="py-24 px-4 sm:px-6 bg-gray-50">',
    '          <div className="mx-auto max-w-3xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">Discover ' + esc(config.projectName) + '</h2>',
    '            <p className="text-gray-600 leading-relaxed text-lg whitespace-pre-line">',
    "              {'" + esc(content.aboutSection) + "'}",
    '            </p>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Features */}',
    '        <section className="py-24 px-4 sm:px-6 bg-white">',
    '          <div className="mx-auto max-w-6xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 text-center mb-16">What Makes It Special</h2>',
    '            <div className="grid gap-12 sm:grid-cols-2 lg:grid-cols-3">',
    '              {features.map((f, i) => (',
    '                <div key={i} className="text-center">',
    '                  <span className="text-4xl">{f.icon}</span>',
    '                  <h3 className="mt-4 text-lg font-bold text-gray-900">{f.title}</h3>',
    '                  <p className="mt-2 text-gray-600">{f.description}</p>',
    '                </div>',
    '              ))}',
    '            </div>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Gallery */}',
    '        <section className="py-24 px-4 sm:px-6 bg-gray-50">',
    '          <div className="mx-auto max-w-6xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">Gallery</h2>',
    '            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">',
    '              {[1, 2, 3, 4, 5, 6].map((n) => (',
    '                <div key={n} className="aspect-[4/3] overflow-hidden rounded-xl bg-gray-200">',
    '                  <img src={"/images/gallery-" + n + ".jpg"} alt={"Gallery " + n} className="h-full w-full object-cover hover:scale-105 transition-transform duration-500" />',
    '                </div>',
    '              ))}',
    '            </div>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Location */}',
    '        <section className="py-24 px-4 sm:px-6 bg-white">',
    '          <div className="mx-auto max-w-3xl text-center">',
    '            <h2 className="text-3xl font-bold text-gray-900 mb-8">The Neighborhood</h2>',
    '            <p className="text-gray-600 leading-relaxed text-lg whitespace-pre-line">',
    "              {'" + esc(content.locationDescription) + "'}",
    '            </p>',
    '          </div>',
    '        </section>',
    '',
    '        {/* FAQ */}',
    '        <section className="py-24 px-4 sm:px-6 bg-gray-50">',
    '          <div className="mx-auto max-w-3xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">Frequently Asked Questions</h2>',
    '            <div className="rounded-xl bg-white px-6 shadow-sm border border-gray-100">',
    '              {faqs.map((f, i) => <FAQ key={i} question={f.question} answer={f.answer} />)}',
    '            </div>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Second Form */}',
    '        <section className="py-24 px-4 sm:px-6 bg-gray-900">',
    '          <div className="mx-auto max-w-lg text-center">',
    '            <h2 className="text-2xl font-bold text-white mb-2">Don&apos;t Miss Out</h2>',
    '            <p className="text-gray-400 mb-8">Register now for priority access and exclusive pricing</p>',
    '            <div className="rounded-2xl bg-white p-8">',
    '              <LeadForm />',
    '            </div>',
    '          </div>',
    '        </section>',
    '      </main>',
    '',
    '      <div className="fixed bottom-0 left-0 right-0 z-50 bg-white border-t border-gray-200 p-3 md:hidden">',
    '        <a href="#register" className="block w-full rounded-lg bg-[#e2725b] py-3 text-center text-sm font-semibold text-white">' + esc(content.ctaText) + '</a>',
    '      </div>',
    '',
    '      <Footer />',
    '    </>',
    '  )',
    '}',
    '',
  ]
  return lines.filter((l) => l !== '').join('\n') + '\n'
}

// ── Template 4: Gallery First ───────────────────────────────────────────────────

const galleryFirst: TemplateGenerator = (config, content) => {
  const lines = [
    faqAccordionComponent(),
    '',
    "import LeadForm from '@/components/LeadForm'",
    "import Footer from '@/components/Footer'",
    '',
    'const features = ' + buildFeaturesArray(content),
    'const faqs = ' + buildFaqsArray(content),
    '',
    'export default function HomePage() {',
    '  return (',
    '    <>',
    '      {/* Top Bar */}',
    '      <header className="bg-white border-b border-gray-100">',
    '        <div className="mx-auto max-w-7xl px-4 sm:px-6 py-6">',
    '          <div className="flex flex-col lg:flex-row lg:items-center gap-8">',
    '            <div className="flex-1">',
    '              <h1 className="text-3xl font-extrabold text-gray-900 sm:text-4xl">' + esc(content.heroHeadline) + '</h1>',
    '              <p className="mt-3 text-gray-600 max-w-xl">' + esc(content.heroSubheadline) + '</p>',
    config.priceRange ? '              <p className="mt-2 text-xl font-bold text-gray-900">' + esc(config.priceRange) + '</p>' : '',
    '            </div>',
    '            <div className="w-full lg:w-96 shrink-0 rounded-xl border border-gray-200 p-5 shadow-sm bg-gray-50">',
    '              <h2 className="text-sm font-bold text-gray-900 mb-3 uppercase tracking-wide">' + esc(content.ctaText) + '</h2>',
    '              <LeadForm compact />',
    '            </div>',
    '          </div>',
    '        </div>',
    '      </header>',
    '',
    '      <main>',
    '        {/* Gallery Grid */}',
    '        <section className="py-12 px-4 sm:px-6 bg-white">',
    '          <div className="mx-auto max-w-7xl">',
    '            <h2 className="text-2xl font-bold text-gray-900 mb-8">Gallery</h2>',
    '            <div className="grid gap-3 grid-cols-2 lg:grid-cols-4">',
    '              <div className="col-span-2 row-span-2 aspect-square overflow-hidden rounded-xl bg-gray-200">',
    '                <img src="/images/hero.jpg" alt="' + esc(config.projectName) + ' main" className="h-full w-full object-cover hover:scale-105 transition-transform duration-500" />',
    '              </div>',
    '              {[1, 2, 3, 4, 5, 6].map((n) => (',
    '                <div key={n} className="aspect-square overflow-hidden rounded-xl bg-gray-200">',
    '                  <img src={"/images/gallery-" + n + ".jpg"} alt={"Gallery " + n} className="h-full w-full object-cover hover:scale-105 transition-transform duration-500" />',
    '                </div>',
    '              ))}',
    '            </div>',
    '          </div>',
    '        </section>',
    '',
    '        {/* About */}',
    '        <section className="py-20 px-4 sm:px-6 bg-gray-50">',
    '          <div className="mx-auto max-w-4xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 mb-8">About ' + esc(config.projectName) + '</h2>',
    '            <p className="text-gray-600 leading-relaxed text-lg whitespace-pre-line">',
    "              {'" + esc(content.aboutSection) + "'}",
    '            </p>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Features scroll */}',
    '        <section className="py-20 px-4 sm:px-6 bg-white">',
    '          <div className="mx-auto max-w-6xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 mb-10">Features & Amenities</h2>',
    '            <div className="flex gap-4 overflow-x-auto pb-4 snap-x">',
    '              {features.map((f, i) => (',
    '                <div key={i} className="shrink-0 w-72 snap-start rounded-xl border border-gray-200 p-6 hover:shadow-md transition-shadow">',
    '                  <span className="text-3xl">{f.icon}</span>',
    '                  <h3 className="mt-4 font-semibold text-gray-900">{f.title}</h3>',
    '                  <p className="mt-2 text-sm text-gray-600">{f.description}</p>',
    '                </div>',
    '              ))}',
    '            </div>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Location */}',
    '        <section className="py-20 px-4 sm:px-6 bg-gray-50">',
    '          <div className="mx-auto max-w-4xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 mb-8">Location</h2>',
    '            <p className="text-gray-600 leading-relaxed text-lg whitespace-pre-line">{' + "'" + esc(content.locationDescription) + "'" + '}</p>',
    '          </div>',
    '        </section>',
    '',
    '        {/* FAQ */}',
    '        <section className="py-20 px-4 sm:px-6 bg-white">',
    '          <div className="mx-auto max-w-3xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">FAQ</h2>',
    '            <div className="rounded-xl border border-gray-200 px-6">',
    '              {faqs.map((f, i) => <FAQ key={i} question={f.question} answer={f.answer} />)}',
    '            </div>',
    '          </div>',
    '        </section>',
    '      </main>',
    '',
    '      <div className="fixed bottom-0 left-0 right-0 z-50 bg-white border-t border-gray-200 p-3 lg:hidden">',
    '        <a href="#top" className="block w-full rounded-lg bg-[#e2725b] py-3 text-center text-sm font-semibold text-white">' + esc(content.ctaText) + '</a>',
    '      </div>',
    '',
    '      <Footer />',
    '    </>',
    '  )',
    '}',
    '',
  ]
  return lines.filter((l) => l !== '').join('\n') + '\n'
}

// ── Template 5: Minimal Premium ─────────────────────────────────────────────────

const minimalPremium: TemplateGenerator = (config, content) => {
  const lines = [
    faqAccordionComponent(),
    '',
    "import LeadForm from '@/components/LeadForm'",
    "import Footer from '@/components/Footer'",
    '',
    'const features = ' + buildFeaturesArray(content),
    'const faqs = ' + buildFaqsArray(content),
    '',
    'export default function HomePage() {',
    '  return (',
    '    <>',
    '      {/* Hero */}',
    '      <header className="flex min-h-[80vh] flex-col items-center justify-center px-4 py-24 text-center bg-[#faf9f7]">',
    '        <p className="text-xs font-medium uppercase tracking-[0.3em] text-gray-500 mb-6">' + esc(config.developer || config.city || 'A New Standard') + '</p>',
    '        <h1 className="font-serif text-5xl font-light text-gray-900 sm:text-6xl lg:text-7xl leading-tight tracking-tight">' + esc(content.heroHeadline) + '</h1>',
    '        <p className="mt-8 text-lg text-gray-500 max-w-xl leading-relaxed">' + esc(content.heroSubheadline) + '</p>',
    config.priceRange ? '        <p className="mt-6 font-serif text-2xl text-gray-900">' + esc(config.priceRange) + '</p>' : '',
    '        <a href="#register" className="mt-10 rounded-none border-2 border-gray-900 bg-gray-900 px-10 py-4 text-sm font-medium uppercase tracking-widest text-white hover:bg-transparent hover:text-gray-900 transition-all">' + esc(content.ctaText) + '</a>',
    '      </header>',
    '',
    '      <main>',
    '        {/* Divider Image */}',
    '        <div className="h-96 bg-[url(/images/hero.jpg)] bg-cover bg-center bg-fixed" />',
    '',
    '        {/* About */}',
    '        <section className="py-24 px-4">',
    '          <div className="mx-auto max-w-2xl text-center">',
    '            <h2 className="font-serif text-3xl font-light text-gray-900">About the Residence</h2>',
    '            <div className="mt-1 mx-auto h-px w-12 bg-gray-900" />',
    '            <p className="mt-10 text-gray-600 leading-loose whitespace-pre-line">',
    "              {'" + esc(content.aboutSection) + "'}",
    '            </p>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Features */}',
    '        <section className="py-24 px-4 bg-[#faf9f7]">',
    '          <div className="mx-auto max-w-3xl">',
    '            <h2 className="font-serif text-3xl font-light text-gray-900 text-center mb-16">Refined Details</h2>',
    '            <div className="divide-y divide-gray-200">',
    '              {features.map((f, i) => (',
    '                <div key={i} className="flex items-start gap-6 py-6">',
    '                  <span className="text-2xl shrink-0 mt-1">{f.icon}</span>',
    '                  <div>',
    '                    <h3 className="font-medium text-gray-900">{f.title}</h3>',
    '                    <p className="mt-1 text-sm text-gray-500">{f.description}</p>',
    '                  </div>',
    '                </div>',
    '              ))}',
    '            </div>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Registration Form */}',
    '        <section id="register" className="py-24 px-4">',
    '          <div className="mx-auto max-w-md text-center">',
    '            <h2 className="font-serif text-3xl font-light text-gray-900">' + esc(content.ctaText) + '</h2>',
    '            <div className="mt-1 mx-auto h-px w-12 bg-gray-900" />',
    '            <p className="mt-6 text-sm text-gray-500 mb-8">Receive priority access to pricing and floor plans</p>',
    '            <LeadForm />',
    '          </div>',
    '        </section>',
    '',
    '        {/* Location */}',
    '        <section className="py-24 px-4 bg-[#faf9f7]">',
    '          <div className="mx-auto max-w-2xl text-center">',
    '            <h2 className="font-serif text-3xl font-light text-gray-900">The Neighborhood</h2>',
    '            <div className="mt-1 mx-auto h-px w-12 bg-gray-900" />',
    '            <p className="mt-10 text-gray-600 leading-loose whitespace-pre-line">{' + "'" + esc(content.locationDescription) + "'" + '}</p>',
    '          </div>',
    '        </section>',
    '',
    '        {/* FAQ */}',
    '        <section className="py-24 px-4">',
    '          <div className="mx-auto max-w-2xl">',
    '            <h2 className="font-serif text-3xl font-light text-gray-900 text-center mb-12">Questions & Answers</h2>',
    '            <div className="divide-y divide-gray-200">',
    '              {faqs.map((f, i) => <FAQ key={i} question={f.question} answer={f.answer} />)}',
    '            </div>',
    '          </div>',
    '        </section>',
    '      </main>',
    '',
    '      <div className="fixed bottom-0 left-0 right-0 z-50 bg-white/90 backdrop-blur border-t border-gray-100 p-3 md:hidden">',
    '        <a href="#register" className="block w-full border-2 border-gray-900 bg-gray-900 py-3 text-center text-sm font-medium uppercase tracking-widest text-white">' + esc(content.ctaText) + '</a>',
    '      </div>',
    '',
    '      <Footer />',
    '    </>',
    '  )',
    '}',
    '',
  ]
  return lines.filter((l) => l !== '').join('\n') + '\n'
}

// ── Template 6: Map / Location Focused ──────────────────────────────────────────

const mapFocused: TemplateGenerator = (config, content) => {
  const locationText = [config.neighborhood, config.city].filter(Boolean).join(', ') || 'Prime Location'
  const lines = [
    faqAccordionComponent(),
    '',
    "import LeadForm from '@/components/LeadForm'",
    "import Footer from '@/components/Footer'",
    '',
    'const features = ' + buildFeaturesArray(content),
    'const faqs = ' + buildFaqsArray(content),
    '',
    'export default function HomePage() {',
    '  return (',
    '    <>',
    '      {/* Hero with location */}',
    '      <header className="bg-white border-b border-gray-200">',
    '        <div className="mx-auto max-w-7xl px-4 sm:px-6 py-12">',
    '          <p className="text-sm font-medium text-[#e2725b] uppercase tracking-wide">Now Registering</p>',
    '          <h1 className="mt-2 text-4xl font-extrabold text-gray-900 sm:text-5xl">' + esc(content.heroHeadline) + '</h1>',
    '          <p className="mt-3 text-xl text-gray-600">Located in ' + esc(locationText) + '</p>',
    config.priceRange ? '          <p className="mt-2 text-2xl font-bold text-gray-900">' + esc(config.priceRange) + '</p>' : '',
    '        </div>',
    '      </header>',
    '',
    '      <main>',
    '        {/* Map + Form */}',
    '        <section className="bg-gray-50">',
    '          <div className="mx-auto max-w-7xl px-4 sm:px-6 py-12">',
    '            <div className="grid gap-8 lg:grid-cols-5">',
    '              <div className="lg:col-span-3 rounded-xl overflow-hidden bg-gray-200 min-h-[400px] flex items-center justify-center">',
    '                <div className="text-center p-8">',
    '                  <div className="text-5xl mb-4">📍</div>',
    '                  <p className="text-lg font-semibold text-gray-700">' + esc(config.projectName) + '</p>',
    '                  <p className="text-gray-500">' + esc(config.location || locationText) + '</p>',
    '                  <p className="text-xs text-gray-400 mt-4">Map will display here with Google Maps API key</p>',
    '                </div>',
    '              </div>',
    '              <div className="lg:col-span-2">',
    '                <div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">',
    '                  <h2 className="text-lg font-bold text-gray-900 mb-1">' + esc(content.ctaText) + '</h2>',
    '                  <p className="text-sm text-gray-500 mb-5">Get pricing, floor plans & VIP access</p>',
    '                  <LeadForm compact />',
    '                </div>',
    '              </div>',
    '            </div>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Neighborhood Highlights */}',
    '        <section className="py-20 px-4 sm:px-6 bg-white">',
    '          <div className="mx-auto max-w-4xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 mb-8">About the Neighborhood</h2>',
    '            <p className="text-gray-600 leading-relaxed text-lg whitespace-pre-line mb-12">',
    "              {'" + esc(content.locationDescription) + "'}",
    '            </p>',
    '          </div>',
    '        </section>',
    '',
    '        {/* About */}',
    '        <section className="py-20 px-4 sm:px-6 bg-gray-50">',
    '          <div className="mx-auto max-w-4xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 mb-8">About ' + esc(config.projectName) + '</h2>',
    '            <p className="text-gray-600 leading-relaxed text-lg whitespace-pre-line">',
    "              {'" + esc(content.aboutSection) + "'}",
    '            </p>',
    '          </div>',
    '        </section>',
    '',
    '        {/* Features */}',
    '        <section className="py-20 px-4 sm:px-6 bg-white">',
    '          <div className="mx-auto max-w-6xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">Features & Highlights</h2>',
    '            <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">',
    '              {features.map((f, i) => (',
    '                <div key={i} className="rounded-xl bg-gray-50 p-6 border border-gray-100">',
    '                  <span className="text-3xl">{f.icon}</span>',
    '                  <h3 className="mt-4 text-lg font-semibold text-gray-900">{f.title}</h3>',
    '                  <p className="mt-2 text-sm text-gray-600">{f.description}</p>',
    '                </div>',
    '              ))}',
    '            </div>',
    '          </div>',
    '        </section>',
    '',
    '        {/* FAQ */}',
    '        <section className="py-20 px-4 sm:px-6 bg-gray-50">',
    '          <div className="mx-auto max-w-3xl">',
    '            <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">Frequently Asked Questions</h2>',
    '            <div className="rounded-xl bg-white px-6 shadow-sm border border-gray-100">',
    '              {faqs.map((f, i) => <FAQ key={i} question={f.question} answer={f.answer} />)}',
    '            </div>',
    '          </div>',
    '        </section>',
    '      </main>',
    '',
    '      <div className="fixed bottom-0 left-0 right-0 z-50 bg-white border-t border-gray-200 p-3 lg:hidden">',
    '        <a href="#top" className="block w-full rounded-lg bg-[#e2725b] py-3 text-center text-sm font-semibold text-white">' + esc(content.ctaText) + '</a>',
    '      </div>',
    '',
    '      <Footer />',
    '    </>',
    '  )',
    '}',
    '',
  ]
  return lines.filter((l) => l !== '').join('\n') + '\n'
}

// ── Dispatcher ──────────────────────────────────────────────────────────────────

const generators: Record<string, TemplateGenerator> = {
  'hero-focus': heroFocus,
  'split-layout': splitLayout,
  'storytelling': storytelling,
  'gallery-first': galleryFirst,
  'minimal-premium': minimalPremium,
  'map-focused': mapFocused,
}

export function generateTemplatePage(config: ProjectConfig, content: GeneratedContent): string {
  const generator = generators[config.template] || heroFocus
  return generator(config, content)
}
